### ISSUE TITLE
bot telegram

### ISSUE THREAD

**Issue by Lmario76** [salvatorecordiano/ama#2]
Ciao Salvatore,
volevo sapere se era possibile creare due bot telegram su due numeri di cellulare che comunicano tra loro in questo modo:
il primo cellulare invia ogni x minuti (tramite il bot) un messaggio di testo al bot del secondo cellulare
il secondo bot deve mandare una notifica solo se non riceve il messaggio.

**Comment by salvatorecordiano** [comment]
Ciao @Lmario76 quello che chiedi si può fare quasi completamente

**Comment by Lmario76** [comment]
quindi cosa non si potrebbe fare?

**Comment by Lmario76** [comment]
vedi sto cercando di configurare (con tasker) un vecchio smartphone come antifurto satellitare e avevo pensato di utilizzare il bot di telegram come un antijammer

**Comment by salvatorecordiano** [comment]
Se devi fare un antijammer forse è meglio pensare a qualcosa del tipo:

Lasci un telefono nel luogo da monitorare.
Sul telefono con Tasker fai una richiesta HTTP ad un tuo url web ogni 5 secondi.

Sul tuo hosting web verifichi se ti arrivano le richieste HTTP.
Se per 30 secondi non ricevi richieste HTTP potresti mandare una notifica Telegram all'altro telefono sempre con te.

Questa cosa è un sorta di monitoraggio proattivo con un approccio pull.

Non so se mi sono spiegato e ti ho aiutato.

**Comment by Lmario76** [comment]
Così Sarebbe perfetto.
Mi sai indicare qualche tutorial a riguardo.
Perché ho configurato tasker come localizzatore ma mi da errore e quindi
fino a quando non capisco il perché sto usando trova il mio dispositivo di
Google.
Ora ho trovato un tutorial per configurare tasker per avvisarmi quando il
mezzo esce dalla zona sicura (sperando che funzioni) però per quello che
dici tu non ho trovato niente.



Il gio 20 ago 2020, 18:12 Salvatore Cordiano <notifications@github.com> ha
scritto:

**Comment by salvatorecordiano** [comment]
Non conosco un tutorial. Per quanto riguarda la richiesta HTTP qualche anno fa usavo https://play.google.com/store/apps/details?id=com.freehaha.restask, ma anche Tasker dovrebbe far fare tutto

**Comment by Lmario76** [comment]
Grazie mille per l'informazione

Il gio 20 ago 2020, 18:23 Salvatore Cordiano <notifications@github.com> ha
scritto:
